name: Celix Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
      - name: Install conan and lcov
        run: |
          sudo apt-get install -yq --no-install-recommends lcov
          sudo pip install conan
      - name: Setup Conan Profile
        run: |
          conan profile new default --detect
          conan profile update settings.build_type=Debug default
          #Note no backwards compatiblity for gcc5 needed, setting libcxx to c++11.
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Install Dependencies
        env:
          CONAN_BUILD_OPTIONS: |
            -o celix:enable_testing=True
            -o celix:build_all=True
            -o enable_code_coverage=True
        run: |
          #force reequire libcurl 7.64.1, due to a sha256 verify issue in libcurl/7.87.0
          conan install . celix/ci -pr:b default -pr:h default -if build ${CONAN_BUILD_OPTIONS} -b missing --require-override=libcurl/7.64.1
      - name: Build
        run: |
          conan build . -bf build --configure
          conan build . -bf build --build
      - name: Test with coverage
        run: |
          cd build
          make coverage
          lcx="lcov --output-file=coverage.info " && for i in `find . -name "*.info.cleaned"`; do lcx+=" --add-tracefile=$i"; done && $lcx
      - name: Codecov
        uses: codecov/codecov-action@e156083f13aff6830c92fc5faa23505779fbf649
        with:
          file: build/coverage.info
          name: codecov-celix
