name: Celix MacOS

on: [push, pull_request]

jobs:

  build-conan:
    if: false #issues in pubsub tests, disable for now
    runs-on: macOS-latest
    timeout-minutes: 120
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
      - name: Install conan
        run: |
          brew install conan
      - name: Setup Conan Profile
        run: |
          conan profile new default --detect
          conan profile update settings.build_type=Debug default
      - name: Install Dependencies
        env:
          CONAN_BUILD_OPTIONS: |
            -o celix:enable_testing=True
            -o celix:build_all=True
        run: |
          #force reequire libcurl 7.64.1, due to a sha256 verify issue in libcurl/7.87.0
          conan install . celix/ci -pr:b default -pr:h default -if build ${CONAN_BUILD_OPTIONS} -b missing  --require-override=libcurl/7.64.1
      - name: Build
        run: |
          conan build . -bf build --configure
          conan build . -bf build --build
      - name: Test
        run: |
          cd build
          source activate_run.sh
          ctest --verbose
          source deactivate_run.sh

  build-brew:
    runs-on: macOS-latest
    timeout-minutes: 120
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
      - name: Install dependencies
        run: |
          brew update
          brew install lcov zeromq czmq cpputest jansson rapidjson libzip
      - name: Build
        env:
          BUILD_OPTIONS: |
            -DENABLE_TESTING=ON
            -DENABLE_TESTING_DEPENDENCY_MANAGER_FOR_CXX11=ON
            -DENABLE_TESTING_FOR_CXX14=ON
            -DENABLE_ADDRESS_SANITIZER=ON
            -DCMAKE_BUILD_TYPE=Debug
            -DBUILD_SYSLOG_WRITER=OFF
        run: |
          mkdir build install
          cd build
          cmake ${BUILD_OPTIONS} -DCMAKE_INSTALL_PREFIX=../install ..
          make -j && make install
      - name: Test
        run: |
          cd $GITHUB_WORKSPACE/build
          export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH:$(pwd)/utils:$(pwd)/framework:$(pwd)/dfi
          make test ARGS="-V"

